version: '3.8'
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./logs:/app/logs
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
